"""empty message

Revision ID: 0f0542386e80
Revises: 592cfc792fd6
Create Date: 2021-04-29 12:24:46.970216

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f0542386e80'
down_revision = '592cfc792fd6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tutorial_progress',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('tutorial_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['tutorial_id'], ['tutorial.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tutorial_progress')
    # ### end Alembic commands ###
