"""add status column and score column

Revision ID: 303401bfdb82
Revises: baf741bcd21e
Create Date: 2021-05-15 16:46:06.066540

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '303401bfdb82'
down_revision = 'baf741bcd21e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question_answer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('score', sa.Float(precision=10, decimal_return_scale=2), nullable=True))

    with op.batch_alter_table('quiz', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.SmallInteger(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quiz', schema=None) as batch_op:
        batch_op.drop_column('status')

    with op.batch_alter_table('question_answer', schema=None) as batch_op:
        batch_op.drop_column('score')

    # ### end Alembic commands ###
