"""empty message

Revision ID: 592cfc792fd6
Revises: 8afb27421510
Create Date: 2021-04-29 11:41:23.555403

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '592cfc792fd6'
down_revision = '8afb27421510'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tutorial', schema=None) as batch_op:
        batch_op.drop_column('question_sub_title')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tutorial', schema=None) as batch_op:
        batch_op.add_column(sa.Column('question_sub_title', sa.VARCHAR(length=140), nullable=True))

    # ### end Alembic commands ###
