"""add options column to Tutorial table

Revision ID: 651a34293f54
Revises: d8265ec587c8
Create Date: 2021-05-15 16:48:14.888530

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '651a34293f54'
down_revision = 'd8265ec587c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tutorial', schema=None) as batch_op:
        batch_op.add_column(sa.Column('answer', sa.SmallInteger(), nullable=True))
        batch_op.add_column(sa.Column('extra_content', sa.UnicodeText(), nullable=True))
        batch_op.add_column(sa.Column('hint', sa.String(length=140), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tutorial', schema=None) as batch_op:
        batch_op.drop_column('hint')
        batch_op.drop_column('extra_content')
        batch_op.drop_column('answer')

    # ### end Alembic commands ###
