"""empty message

Revision ID: 8afb27421510
Revises: 63ccf5e3e54d
Create Date: 2021-04-29 11:05:32.613701

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8afb27421510'
down_revision = '63ccf5e3e54d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tutorial_progress',
    sa.Column('tutorial_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['tutorial_id'], ['tutorial.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    with op.batch_alter_table('tutorial', schema=None) as batch_op:
        batch_op.add_column(sa.Column('answer', sa.SmallInteger(), nullable=True))
        batch_op.add_column(sa.Column('extra_content', sa.UnicodeText(), nullable=True))
        batch_op.add_column(sa.Column('hint', sa.String(length=140), nullable=True))
        batch_op.add_column(sa.Column('main_content', sa.UnicodeText(), nullable=True))
        batch_op.add_column(sa.Column('question_sub_title', sa.String(length=140), nullable=True))
        batch_op.add_column(sa.Column('question_title', sa.String(length=140), nullable=True))
        batch_op.add_column(sa.Column('subtitle', sa.String(length=140), nullable=True))
        batch_op.drop_column('content')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tutorial', schema=None) as batch_op:
        batch_op.add_column(sa.Column('content', sa.TEXT(), nullable=True))
        batch_op.drop_column('subtitle')
        batch_op.drop_column('question_title')
        batch_op.drop_column('question_sub_title')
        batch_op.drop_column('main_content')
        batch_op.drop_column('hint')
        batch_op.drop_column('extra_content')
        batch_op.drop_column('answer')

    op.drop_table('tutorial_progress')
    # ### end Alembic commands ###
