"""empty message

Revision ID: abb3c9c02572
Revises: 
Create Date: 2021-05-02 11:27:40.725774

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'abb3c9c02572'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tutorial',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=140), nullable=True),
    sa.Column('subtitle', sa.String(length=140), nullable=True),
    sa.Column('main_content', sa.UnicodeText(), nullable=True),
    sa.Column('extra_content', sa.UnicodeText(), nullable=True),
    sa.Column('img_url', sa.String(length=140), nullable=True),
    sa.Column('question_title', sa.String(length=140), nullable=True),
    sa.Column('answer', sa.SmallInteger(), nullable=True),
    sa.Column('hint', sa.String(length=140), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_username'), ['username'], unique=True)

    op.create_table('tutorial_progress',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('tutorial_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['tutorial_id'], ['tutorial.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tutorial_progress')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_username'))
        batch_op.drop_index(batch_op.f('ix_user_email'))

    op.drop_table('user')
    op.drop_table('tutorial')
    # ### end Alembic commands ###
