"""add options column to question table

Revision ID: eee5bc3faa7f
Revises: 303401bfdb82
Create Date: 2021-05-15 16:46:46.118058

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eee5bc3faa7f'
down_revision = '303401bfdb82'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.add_column(sa.Column('option_four', sa.String(length=40), nullable=True))
        batch_op.add_column(sa.Column('option_one', sa.String(length=40), nullable=True))
        batch_op.add_column(sa.Column('option_three', sa.String(length=40), nullable=True))
        batch_op.add_column(sa.Column('option_two', sa.String(length=40), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.drop_column('option_two')
        batch_op.drop_column('option_three')
        batch_op.drop_column('option_one')
        batch_op.drop_column('option_four')

    # ### end Alembic commands ###
